#Created by Ramon
#Date: 7.3.22

GET http://localhost:3333/s/SEawJG
Accept: application/json

###

GET http://localhost:3333/cookie
Accept: application/json

###
GET http://localhost:3333/s
Accept: application/json