#Created by Ramon
#Date: 7.3.22

GET http://localhost:3333/s/SEawJG
Accept: application/json

###

GET http://localhost:3333/cookie
Accept: application/json

###
GET http://localhost:3333/s
Accept: application/json

###
POST http://localhost:3333/create
Accept: application/json

{ "title": "jordan", "content": "du", "cookie": "mongo"}

###
POST http://localhost:3333/edit
Accept: application/json

{ "id":"stJAHs", "title": "jordan", "content": "spastigrind", "cookie": "mongo"}

###
POST http://localhost:3333/delete
Accept: application/json

{ "id":"OLxuS0", "cookie": "IkXo6uRUikQ8x35bFtZaRt8SCXt0wD23mqyVlYUjOGTP8IW6oeTFIKYIDxHppaPW83t38"}

###
POST http://localhost:3333/deleteallbycookie
Accept: application/json

{"cookie": "mongo"}